services:
  app:
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    env_file:
      - .env.test
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:16
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  redis:
    image: redis:latest
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  nginx:
    build: ./infra/nginx
    depends_on:
      - app
    volumes:
      - ./media:/media:ro
      - ./static:/static:ro
      - ./logs/nginx:/var/log/nginx
    env_file:
      - .env.test
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_test_data:
