version: '3.8'

services:
  app:
    build: ./backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/media:/app/media:ro
      - ./backend/src/static:/app/src/static:ro
    depends_on:
      - app


volumes:
  postgres_data: