services:
  backend:
    build:
      context: ./backend
    image: job_scope_backend:latest  # можно использовать как ссылку

  app:
    image: job_scope_backend:latest
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data  # RDB + AOF
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
#    ports:
#      - "6379:6379"

  flower:
    image: mher/flower:latest
    container_name: flower
    command: celery --broker=redis://redis:6379/0 flower
    env_file:
      - .env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

  celery:
    image: job_scope_backend:latest
    command: celery -A src.core.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    depends_on:
      - redis
      - app

  celery-beat:
    image: job_scope_backend:latest
    env_file:
      - .env
    command: celery -A src.core.celery beat --loglevel=info
    volumes:
      - ./backend:/app
      - ./logs/fastapi:/app/logs
      - ./media:/media
      - ./static:/static
    depends_on:
      - redis
      - celery

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./logs/postgresql:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    ports:
#      - "5432:5432"

  nginx:
    build: ./infra/nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./media:/media:ro
      - ./static:/static:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    container_name: logstash
    env_file:
      - .env
    environment:
        - LS_JAVA_OPTS=${LS_JAVA_OPTS}
    volumes:
      - ./infra/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./infra/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    env_file:
      - .env
    environment:
      - discovery.type=${ES_DISCOVERY_TYPE}
      - xpack.security.enabled=${ES_XPACK_SECURITY}  # Отключаем авторизацию для локальной разработки
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}  # Ограничение памяти
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    env_file:
      - .env
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  filebeat:
    build: ./infra/elk/filebeat
    env_file:
      - .env
    depends_on:
      - app
      - logstash
      - kibana
    volumes:
      - ./logs/fastapi:/app/logs:ro  # Папка с логами приложения
      - ./logs/nginx:/var/log/nginx:ro  # Логи nginx
      - ./logs/postgresql:/var/log/postgresql:ro
      - filebeat_registry:/usr/share/filebeat/data
    restart: on-failure

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
#    ports:
#      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/postgres?sslmode=disable
#    ports:
#      - "9187:9187"
    restart: always
    depends_on:
      - db

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - '-nginx.scrape-uri=http://nginx/stub_status'
#    ports:
#     - "9113:9113"
    restart: always
    depends_on:
      - nginx

volumes:
  redis_data:
  postgres_data:
  filebeat_registry:
  elastic_data:
    driver: local
  prometheus_data:
  grafana_data: