"""initial: users, vacations

Revision ID: 4e9be30074df
Revises: 
Create Date: 2025-03-24 18:26:01.816475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9be30074df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=5), nullable=True),
    sa.Column('salary_gross', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('area_name', sa.String(length=256), nullable=True),
    sa.Column('employer_name', sa.String(length=512), nullable=True),
    sa.Column('employment', sa.String(length=50), nullable=True),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('has_test', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vacancies_pkey')),
    sa.UniqueConstraint('source_name', 'source_id', name='uq_vacancy_source')
    )
    op.create_index(op.f('vacancies_created_at_idx'), 'vacancies', ['created_at'], unique=False)
    op.create_index(op.f('vacancies_is_archived_idx'), 'vacancies', ['is_archived'], unique=False)
    op.create_index(op.f('vacancies_published_at_idx'), 'vacancies', ['published_at'], unique=False)
    op.create_index(op.f('vacancies_source_id_idx'), 'vacancies', ['source_id'], unique=False)
    op.create_index(op.f('vacancies_source_name_idx'), 'vacancies', ['source_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('vacancies_source_name_idx'), table_name='vacancies')
    op.drop_index(op.f('vacancies_source_id_idx'), table_name='vacancies')
    op.drop_index(op.f('vacancies_published_at_idx'), table_name='vacancies')
    op.drop_index(op.f('vacancies_is_archived_idx'), table_name='vacancies')
    op.drop_index(op.f('vacancies_created_at_idx'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
